# ----------------------------------------------------------------------------
# Basic setup
# ----------------------------------------------------------------------------
dataset: "tum-3"
seed: 42
image:
  height: 480
  width: 640


# ----------------------------------------------------------------------------
# tracking options
# ----------------------------------------------------------------------------
feature_tracking_method: 1
  # 1: deep optical flow

tracking_method: 3 
  # 3: hybrid

compute_2d2d_pose:
  ransac:
    reproj_thre: 0.2
    repeat: 10
  validity:
    method: flow+chei
    min_flow: 5 

PnP:
  ransac:
    iter: 1000
    reproj_thre: 1
    repeat: 5
  kp_src: kp_list # [kp_list, kp_best]

# translation scale
translation_scale:
  ransac:
    min_samples: 3
    max_trials: 100
    stop_prob: 0.99
    thre: 1
  kp_src: kp_list # [kp_list, kp_best]

# ----------------------------------------------------------------------------
# Deep single-view depth
# ----------------------------------------------------------------------------
depth:
  depth_src: 0
  max_depth: 50
  min_depth: 0
  pretrained_model: model_zoo/depth/kitti_odom/stereo/

# ----------------------------------------------------------------------------
# Deep Optical Flow
# ----------------------------------------------------------------------------
deep_flow:
  forward_backward: True
  num_kp: 20000
  kp_sel_method: bestN
  network: liteflow  
    # liteflow: LiteFlowNet
  flow_net_weight: model/network-default.pytorch
  batch_size: 1
  precomputed_flow: 

crop:
  depth_crop: [[0.1, 0.9], [0.1, 0.9]]
  flow_crop: [[0.1, 0.9], [0.1, 0.9]]

# ----------------------------------------------------------------------------
# Ground truth availability
# ----------------------------------------------------------------------------
available:
  gt_pose: True
