BASE_TASK_CONFIG_PATH: "./config/tasks/pointnav_gibson.yaml"
ENVIRONMENT:
  MAPSCALE: 0.03
  CHANGE_FREQ: 25
  LOCAL_GOAL_DIST: 1.25
  LOCAL_GOAL_SUCCESS_DIST: 0.125

TRAINER_NAME: "ppo"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 2
TORCH_GPU_ID: 2
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "./algorithm_data/tbd"
VIDEO_DIR: "./algorithm_data/video_dir"
TEST_EPISODE_COUNT: 20
EVAL_CKPT_PATH_DIR: "./algorithm_data/data/new_checkpoints"
NUM_PROCESSES: 2
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "./algorithm_data/new_checkpoints"
NUM_UPDATES: 4000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 50

AGENT:
  MODEL_PATH: "./algorithm_data/new_checkpoints/ckpt.6.pth"
  PTH_GPU_ID: 2
  INPUT_TYPE: "rgb"
